name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  percent_indicator:
  image_picker:
  pinch_zoom:
  image_gallery_saver:
  http:
  path_provider:
  splashscreen:
  flutter_launcher_icons:
  awesome_dialog:
  carousel_slider:
  permission_handler:
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/images/circle.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  